ALTER TABLE crop_catalog
  ADD COLUMN IF NOT EXISTS co2_min NUMERIC(6,1),
  ADD COLUMN IF NOT EXISTS co2_max NUMERIC(6,1),
  ADD COLUMN IF NOT EXISTS vpd_min NUMERIC(4,2),
  ADD COLUMN IF NOT EXISTS vpd_max NUMERIC(4,2),
  ADD COLUMN IF NOT EXISTS ppfd_min NUMERIC(6,1),
  ADD COLUMN IF NOT EXISTS ppfd_max NUMERIC(6,1),
  ADD COLUMN IF NOT EXISTS solution_temp_min NUMERIC(4,1),
  ADD COLUMN IF NOT EXISTS solution_temp_max NUMERIC(4,1);
